// Package securevault asynchronously archives unredacted HTTP exchanges in a
// customer-owned S3 bucket.
//
// Each record is envelope-encrypted with a unique AES-256 data key generated by
// AWS KMS. Only the KMS-encrypted copy of that key is stored beside the AES-GCM
// ciphertext. Failed work is encrypted with a separate customer-owned local
// spool key and retried from disk, keeping AWS outages outside the request path.
//
// The package deliberately has no dependency on proxy routing or caching.
package securevault
